export const images = {
    camera:require("../assets/images/camera.png"),
    down_arrow:require("../assets/images/down_arrow.png"),
    icon:require("../assets/images/icon.png"),
    eye_off:require("../assets/images/eye_off.png"),
    eye:require("../assets/images/eye.png"),
    check:require("../assets/images/check.png"),

    clock:require("../assets/images/clock.png"),
    phone:require("../assets/images/phone.png"),
    edit:require("../assets/images/edit.png"),
    refresh:require("../assets/images/refresh.png"),
    back_arrow:require("../assets/images/back_arrow.png"),
    google:require("../assets/images/google.png"),
    apple:require("../assets/images/apple.png"),
    github:require("../assets/images/github.png"),
    balls_sports:require("../assets/images/balls_sports.png"),
    filter:require("../assets/images/filter.png"),
    table_tennis:require("../assets/images/table_tennis.png"),
    pin:require("../assets/images/pin.png"),
    profile_img:require("../assets/images/profile_img.jpg"),
    home:require("../assets/images/home.png"),
    event:require("../assets/images/event.png"),
    schedule:require("../assets/images/schedule.png"),
    football:require("../assets/images/football.png"),
    profile:require("../assets/images/profile.png"),
    user:require("../assets/images/user.png"),
    power_off:require("../assets/images/power_off.png"),

    calendar:require("../assets/images/calendar.png"),
    ball:require("../assets/images/ball.png"),
    notification:require("../assets/images/notification.png"),


    master_card:require("../assets/images/master_card.png"),
    visa_card:require("../assets/images/visa_card.png"),
    marketing:require("../assets/images/marketing.png"),
    plus:require("../assets/images/plus.png"),
    signature:require("../assets/images/signature.png"),
    phone_number:require("../assets/images/phone_number.png"),
    shirt:require("../assets/images/shirt.png"),
    heart:require("../assets/images/heart.png"),
    card:require("../assets/images/card.png"),
    privacy:require("../assets/images/privacy.png"),
    help:require("../assets/images/help.png"),
    logout:require("../assets/images/logout.png"),
    star:require("../assets/images/star.png"),
    cup:require("../assets/images/cup.png"),
    email:require("../assets/images/email.png"),
    next_arrow:require("../assets/images/next_arrow.png"),
    coming_soon:require("../assets/images/coming_soon.png"),

    
    
}
